[package]
name = "fermentation"
description = "The good kind of decay; forward decay."
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/misalcedo/fermentation"

[dependencies]
