[package]
name = "fermentation"
description = "The good kind of decay; forward decay."
version = "0.5.1"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/misalcedo/fermentation"

[dependencies]
